spring.application.name=Attendence
spring.datasource.url=jdbc:mysql://localhost:3306/attendance_db
spring.datasource.username=root
spring.datasource.password=stalingrad1942
spring.jpa.hibernate.ddl-auto=update
